// Code generated by Kitex v0.6.2. DO NOT EDIT.

package douyinpublishactionservice

import (
	action "Douyin_Demo/kitex_gen/douyin/publish/action"
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return douyinPublishActionServiceServiceInfo
}

var douyinPublishActionServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "DouyinPublishActionService"
	handlerType := (*action.DouyinPublishActionService)(nil)
	methods := map[string]kitex.MethodInfo{
		"DouyinPublishAction": kitex.NewMethodInfo(douyinPublishActionHandler, newDouyinPublishActionArgs, newDouyinPublishActionResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "douyin.publish.action",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.6.2",
		Extra:           extra,
	}
	return svcInfo
}

func douyinPublishActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(action.DouyinPublishActionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(action.DouyinPublishActionService).DouyinPublishAction(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *DouyinPublishActionArgs:
		success, err := handler.(action.DouyinPublishActionService).DouyinPublishAction(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DouyinPublishActionResult)
		realResult.Success = success
	}
	return nil
}
func newDouyinPublishActionArgs() interface{} {
	return &DouyinPublishActionArgs{}
}

func newDouyinPublishActionResult() interface{} {
	return &DouyinPublishActionResult{}
}

type DouyinPublishActionArgs struct {
	Req *action.DouyinPublishActionRequest
}

func (p *DouyinPublishActionArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(action.DouyinPublishActionRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DouyinPublishActionArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DouyinPublishActionArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DouyinPublishActionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in DouyinPublishActionArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *DouyinPublishActionArgs) Unmarshal(in []byte) error {
	msg := new(action.DouyinPublishActionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DouyinPublishActionArgs_Req_DEFAULT *action.DouyinPublishActionRequest

func (p *DouyinPublishActionArgs) GetReq() *action.DouyinPublishActionRequest {
	if !p.IsSetReq() {
		return DouyinPublishActionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DouyinPublishActionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DouyinPublishActionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DouyinPublishActionResult struct {
	Success *action.DouyinPublishActionResponse
}

var DouyinPublishActionResult_Success_DEFAULT *action.DouyinPublishActionResponse

func (p *DouyinPublishActionResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(action.DouyinPublishActionResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DouyinPublishActionResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DouyinPublishActionResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DouyinPublishActionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in DouyinPublishActionResult")
	}
	return proto.Marshal(p.Success)
}

func (p *DouyinPublishActionResult) Unmarshal(in []byte) error {
	msg := new(action.DouyinPublishActionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DouyinPublishActionResult) GetSuccess() *action.DouyinPublishActionResponse {
	if !p.IsSetSuccess() {
		return DouyinPublishActionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DouyinPublishActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*action.DouyinPublishActionResponse)
}

func (p *DouyinPublishActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DouyinPublishActionResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) DouyinPublishAction(ctx context.Context, Req *action.DouyinPublishActionRequest) (r *action.DouyinPublishActionResponse, err error) {
	var _args DouyinPublishActionArgs
	_args.Req = Req
	var _result DouyinPublishActionResult
	if err = p.c.Call(ctx, "DouyinPublishAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
