// Code generated by Kitex v0.6.2. DO NOT EDIT.
package douyinpublishactionservice

import (
	action "Douyin_Demo/kitex_gen/douyin/publish/action"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler action.DouyinPublishActionService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
