// Code generated by Kitex v0.6.2. DO NOT EDIT.

package feedservice

import (
	feed "Douyin_Demo/kitex_gen/douyin/feed"
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return feedServiceServiceInfo
}

var feedServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FeedService"
	handlerType := (*feed.FeedService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetVideoFeed": kitex.NewMethodInfo(getVideoFeedHandler, newGetVideoFeedArgs, newGetVideoFeedResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "douyin.feed",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.6.2",
		Extra:           extra,
	}
	return svcInfo
}

func getVideoFeedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(feed.FeedRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(feed.FeedService).GetVideoFeed(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *GetVideoFeedArgs:
		success, err := handler.(feed.FeedService).GetVideoFeed(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetVideoFeedResult)
		realResult.Success = success
	}
	return nil
}
func newGetVideoFeedArgs() interface{} {
	return &GetVideoFeedArgs{}
}

func newGetVideoFeedResult() interface{} {
	return &GetVideoFeedResult{}
}

type GetVideoFeedArgs struct {
	Req *feed.FeedRequest
}

func (p *GetVideoFeedArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(feed.FeedRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetVideoFeedArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetVideoFeedArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetVideoFeedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in GetVideoFeedArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *GetVideoFeedArgs) Unmarshal(in []byte) error {
	msg := new(feed.FeedRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetVideoFeedArgs_Req_DEFAULT *feed.FeedRequest

func (p *GetVideoFeedArgs) GetReq() *feed.FeedRequest {
	if !p.IsSetReq() {
		return GetVideoFeedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetVideoFeedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetVideoFeedArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetVideoFeedResult struct {
	Success *feed.FeedResponse
}

var GetVideoFeedResult_Success_DEFAULT *feed.FeedResponse

func (p *GetVideoFeedResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(feed.FeedResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetVideoFeedResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetVideoFeedResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetVideoFeedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in GetVideoFeedResult")
	}
	return proto.Marshal(p.Success)
}

func (p *GetVideoFeedResult) Unmarshal(in []byte) error {
	msg := new(feed.FeedResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetVideoFeedResult) GetSuccess() *feed.FeedResponse {
	if !p.IsSetSuccess() {
		return GetVideoFeedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetVideoFeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*feed.FeedResponse)
}

func (p *GetVideoFeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetVideoFeedResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetVideoFeed(ctx context.Context, Req *feed.FeedRequest) (r *feed.FeedResponse, err error) {
	var _args GetVideoFeedArgs
	_args.Req = Req
	var _result GetVideoFeedResult
	if err = p.c.Call(ctx, "GetVideoFeed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
