# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run code review
        run: |
          go mod tidy
          go build
          go test
          # Run code review tool here
      - name: Glitch Merge to Main
        if: success()
        # You may pin to the exact commit or the version.
        # uses: leozusa/Glitch-Merge-To-Main@6acc394235acaf0d2203d833eb8781c10cecf4ac
        uses: leozusa/Glitch-Merge-To-Main@v1.1
